### ISSUE TITLE
outdated websockets dependency

### ISSUE THREAD

**Issue by jakobwgnr** [GenFirst/nest-status-monitor#15]
nest-status-monitor is depending on an old version of  @nestjs/websockets --> ^6.11.8
This is now causing warnings when running the core on v7..

npm WARN @nestjs/websockets@6.11.11 requires a peer of @nestjs/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nestjs/websockets@6.11.11 requires a peer of @nestjs/core@^6.0.0 but none is installed. You must install peer dependencies yourself.

Please update dependency.

Thanks, Jakob

**Comment by ivanvs** [comment]
Dependency is updated.
