### ISSUE TITLE
Package update

### ISSUE THREAD

**Issue by segedy01** [GenFirst/nest-status-monitor#6]
Any reason nest-status-monitor hasn't been updated to reflect the changes on this PR [5](https://github.com/GenFirst/nest-status-monitor/pull/5) for the nest 6.1.1 changes?
Also, is updating the package on NPM something I can do? If yes, you can drop the steps here.

**Comment by ivanvs** [comment]
Sorry, I forgot to do that. I have published new version on NPM. It is v0.1.0. Could you check it?

**Comment by segedy01** [comment]
Great. Thanks!
