### ISSUE TITLE
new handlebars vulnerabilities

### ISSUE THREAD

**Issue by shellthor** [GenFirst/nest-status-monitor#9]
It looks like there are 3 new high priority vulnerabilities for the handlebars package.

- https://npmjs.com/advisories/1316
- https://npmjs.com/advisories/1324
- https://npmjs.com/advisories/1325

I can open a PR to resolve, but was wondering if you were also open to upgrading all of the dependencies to their latest versions?

**Comment by ivanvs** [comment]
Hi @shellthor, yes I can update all dependencies. I will do this during this week. Thank you for your help.

**Comment by ivanvs** [comment]
Hi @shellthor, new version of package is released. dependencies are updated :) 

Thank you one more time for your help!
